### PR TITLE
Please add QQCS to the list of participating projects.

### PR DESCRIPTION
**Pull request by dde**

### CODE REVIEW

**Comment by crazy4pi314** [comment]
Hi @dde! I wanted to reach out and discuss this with you, as I currently don't have any more event funds to cover bounties for more projects. Is this something your organization/institution can contribute? If you want to have a quick chat about this, [send me an email](mailto:sarah@unitary.fund) and I'll get back to you asap.

**Comment by dde** [comment]
Thanks for getting back to me.  I can cover the bounties.  How should I handle it?  Make a donation to the Unitaryfund?

I will be modifying the issues slightly.  I am going to remove Issue 14, as I think it is too difficult to expect a reasonable completion by someone not intimately familiar with the code.  The others amount to $275.00.  Is this OK?

**Comment by crazy4pi314** [comment]
> Make a donation to the Unitaryfund?

Yeah that works, [send me and email](mailto:sarah@unitary.fund) to coordinate.

> I will be modifying the issues slightly...

Yeah that is totally fine. I definantly recommend having a good range of difficulties and quantum/non-quantum tasks to get folks involved. If people get familiar with their projects with an easier starting project, they are well prepared to try some harder stuff later!

**Comment by dde** [comment]
I will modify the issues slightly and make another Pull Request.

**Pull request closed without merging**
